spring.application.name=service-registry
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.config.import=optional:configserver:http://localhost:8888

info.app.name=KartNova Service Registry
info.app.description=Service discovery server for KartNova microservices
info.app.version=0.0.1-SNAPSHOT