# IMPORTANT:
# Ye name config-server ke file name se match hona chahiye
spring.application.name=api-gateway

# Config server se external configuration load karne ke liye
spring.config.import=optional:configserver:http://localhost:8888

# Local default profile
spring.profiles.active=default

# IMPORTANT:
# API Gateway ko servlet nahi, reactive mode me run karna hai
spring.main.web-application-type=reactive

# Useful actuator endpoints
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always