# ================================
# Basic Service Identity
# ================================

# Important:
# Ye name config-server file name aur Eureka registration ke saath match hona chahiye
spring.application.name=api-gateway

# Gateway application port
server.port=8080

# ================================
# Eureka Client Configuration
# ================================

# Important:
# Gateway ko Eureka server par register hona hai aur baaki services discover bhi karni hain
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Local development me IP dikhana useful hota hai
eureka.instance.prefer-ip-address=true

#================================
# Gateway discovery support
# ================================
# IMPORTANT:
# New property names use karo to migration warning band ho jayegi
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# ================================
# Static route definitions
# ================================
# Auth service route
spring.cloud.gateway.server.webflux.routes[0].id=auth-service-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**

# User service route
spring.cloud.gateway.server.webflux.routes[1].id=user-service-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/users/**

# ================================
# Actuator / Monitoring
# ================================

# IMPORTANT:
# Gateway actuator endpoint ko explicitly enable access dena hota hai
management.endpoint.gateway.access=read-only

# Expose gateway endpoint over HTTP
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

info.app.name=KartNova API Gateway
info.app.description=Entry point for KartNova microservices
info.app.version=0.0.1-SNAPSHOT