spring.application.name=config-server
server.port=8888

management.endpoints.web.exposure.include=health,info,env,refresh
management.endpoint.health.show-details=always

spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:./config-repo

info.app.name=KartNova Config Server
info.app.description=Centralized configuration server for KartNova microservices
info.app.version=0.0.1-SNAPSHOT